### ISSUE TITLE
IMU for motion capture

### ISSUE THREAD

**Issue by NoLoPhe** [hipnuc/products#3]
你好! Dear HiPNUC team!

I am a student at the University of Danang in Vietnam.

I want to reproduce the results of the Transpose paper "Real-time 3D Human Translation and Pose Estimation with Six Inertial Sensors".
I want to choose IMU for motion capture system using 6 IMU. 
I want to use HiPNUC's IMU but I don't know which one to choose. IMU 6-DOF or 9-DOF: Hi226, Hi229 or CH100.
The model input data has the following structure [Here](https://github.com/SlimeVRX/SlimeVRX/tree/main/transpose)
Final, I use the results of the article into VRChat.

About Transpose paper: [paper] [webpage] [Here](https://xinyu-yi.github.io/TransPose/)
Results displayed in Unity3D at 60Hz [Here](https://twitter.com/Tn23008624/status/1500153059066146816)
Results in the paper is 90 FPS running on laptop with Intel(R) Core(TM) CPU i7-10750H and NVIDIA RTX2080 Super.
Results on my laptop is 10 FPS with only CPU i5-5200U.
I wrote a tutorial to run the code [Here](https://github.com/SlimeVRX/TransPose/blob/main/install_note.md)

**Comment by yandld** [comment]
Hi,

This a HiPNUC engineer Alex Yang.
Actually I didn't use TransPose before but I noticed it long times ago.
For the motion capture application. I suggest to use HI221.(www.hipnuc.com)
https://www.hipnuc.com/resource?type=download&p=imu_download

I'am not sure if you able to read um and related material in Chinese version(only Chinese version available now). If not, you can contact our Taiwan department.(https://www.hipnuc.com/tw/contact.html) for international support.

If possible, you can register WeChat and contact with me. my WeChat ID: 15701256050

**Comment by NoLoPhe** [comment]
Hi @yandld !

I have read your series of articles on Zhihu, it gives me a lot of knowledge.

Thank you very much!

**Comment by yandld** [comment]
Hi NoLoPhe,

So you can read in Chinese,? You can add me WeChat to discuss detail about Implement Transpose.

**Comment by NoLoPhe** [comment]
Yes, I can translate Chinese. 
I have a Wechat account, add me! Nice to discuss Transpose.

The HI221 IMU parameters are the same as the HI229.
The parameters of IMU CH100 give better than HI229.
I don't know what is the best option for motion capture?

**Comment by yandld** [comment]
HI221 can do wirelesss transmition.

all other products(HI226,HI229 CH100 CH110) cannot.(only wired transmition)

**Comment by NoLoPhe** [comment]
I'm not interested in wireless capabilities yet. I'm interested in which sensor is best calibrated for motion capture. Low drift of IMU after a long time.

**Comment by NoLoPhe** [comment]
My ID WeChat: wxid_xyyykpjkiygw22
